// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUl3tUlxe-E4kb5AqcBCKff4Hdumn8U7s',
    appId: '1:136198181516:web:716589e75a9036f1fe61a9',
    messagingSenderId: '136198181516',
    projectId: 'flutter-student-database-2835e',
    authDomain: 'flutter-student-database-2835e.firebaseapp.com',
    databaseURL: 'https://flutter-student-database-2835e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-student-database-2835e.firebasestorage.app',
    measurementId: 'G-H3TWF740RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9kwLvEJ0SZZ0S4eE7BLJ5oJIwWnBr4wc',
    appId: '1:136198181516:android:76e231ba6bd5c3fbfe61a9',
    messagingSenderId: '136198181516',
    projectId: 'flutter-student-database-2835e',
    databaseURL: 'https://flutter-student-database-2835e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-student-database-2835e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX2sgvJsrkeLUhMDEqFloUykUgS9g8b2g',
    appId: '1:136198181516:ios:4eaaa8d19dbe09c1fe61a9',
    messagingSenderId: '136198181516',
    projectId: 'flutter-student-database-2835e',
    databaseURL: 'https://flutter-student-database-2835e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-student-database-2835e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDatabaseApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX2sgvJsrkeLUhMDEqFloUykUgS9g8b2g',
    appId: '1:136198181516:ios:4eaaa8d19dbe09c1fe61a9',
    messagingSenderId: '136198181516',
    projectId: 'flutter-student-database-2835e',
    databaseURL: 'https://flutter-student-database-2835e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-student-database-2835e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDatabaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUl3tUlxe-E4kb5AqcBCKff4Hdumn8U7s',
    appId: '1:136198181516:web:ebe68cb720bb7455fe61a9',
    messagingSenderId: '136198181516',
    projectId: 'flutter-student-database-2835e',
    authDomain: 'flutter-student-database-2835e.firebaseapp.com',
    databaseURL: 'https://flutter-student-database-2835e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-student-database-2835e.firebasestorage.app',
    measurementId: 'G-B6RTW5Z3FY',
  );
}
